# Site settings
baseURL = "/"
languageCode = "en-US"
title = "Houston Perrett"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Houston Perrett"
  description = "Hi. I'm Houston. I spend my days solving actuarial problems and thinking about the interactions of technology, insurance, and society."
  shareImage = "images/social.jpg"
  twitterHandle = "HoustonPerrett"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2017 Houston Perrett"

  # Section - Content
  [params.content]
    name = "Houston Perrett"
    tagline = "Actuary. Developer. Tech Enthusiast."
    bio = "Hi. I'm Houston. I spend my days solving actuarial problems and thinking about the interactions of technology, insurance, and society. I try to combine my background in programming and my expertise of the actuarial and financial domains to drive the industry and profession forward."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background-1-3.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://blog.houstonp.com/"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:h@houstonp.com"

      [[params.links.list1.link]]
        text = "Resume"
        url = "https://resume.houstonp.com/"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/HoustonPerrett"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://linkedin.com/in/HoustonPerrett"

      [[params.links.list2.link]]
        text = "Github"
        url = "https://github.com/Houstonwp"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Actuarial Guide"
        url = "https://actuarialguide.com/"

      [[params.links.list3.link]]
        text = "DSM Foodie"
        url = "https://dsmfoodie.com/"

      [[params.links.list3.link]]
        text = "Heartland Greyhound Adoption"
        url = "https://hga.dog/"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
